# 网站的根URL
baseurl = "https://techqu.github.io/"
# 首页的标题
title = "Quguang's Blog"

subtitle = "专注于Android、Java、Go语言(golang)、移动互联网、项目管理、软件架构"
keywords = "java,java语言,java语言笔记,techqu,quguang,瞿广,博客,项目管理,python,软件架构,公众号,小程序"
description = "专注于IT互联网，包括但不限于Java语言(golang)、Go、Android、Python、项目管理、抖音分析、软件架构等"



# 设置使用的主题
theme = "maupassant"
# 设置网站默认的语言，所有的语言翻译文件在i18n目录下，文件名于此处配置的语言代码相同
languageCode = "zh"
defaultContentLanguage = "zh"
# 值为空的话则不启用disqus，因为需要翻墙才能访问，所以我们不启用
disqusShortname = ""
# 取消默认的代码高亮，我们使用prism代码高亮
pygmentsUseClasses = false
pygmentCodeFences = true

## 保持分类的原始名字（false会做转小写处理）
preserveTaxonomyNames = true
## 是否禁止URL Path转小写
disablePathToLower = true

# 每页显示的文章数量用于分页
paginate = 5

[menu]

# 板块化分
# 权重对应在页面上显示的次序






[[menu.main]]
  identifier = "archives"
   name = "归档"
   url = "/archives/"
   weight = 3

[[menu.main]]
   name = "markdown示例"
   url = "/markdown/"
   weight = 7


[[menu.main]]
   name = "学习路线图"
   url = "/roadmap/"
   weight = 5

[[menu.main]]
    name = "简历模版"
    url  = "/resume/"
    weight = 6

[[params.links]]
  title = "ImportNew - 专注Java & Android 技术分享"
  name = "ImportNew - 专注Java & Android 技术分享"
  url = "http://www.importnew.com/"
[[params.links]]
  title = "springboot中文索引"
  name = "springboot中文索引"
  url = "http://springboot.fun/"
[[params.links]]
  title = "springcloud中文索引"
  name = "springcloud中文索引"
  url = "http://springcloud.fun/"


#[[params.ads]]
#  title = "广告位测试"
#  url = "https://promotion.aliyun.com/ntms/act/vmpt/aliyun-group/home.html?userCode=jdg9oj97"
#  img = "https://img.alicdn.com/tfs/TB17qJhXpzqK1RjSZFvXXcB7VXa-200-126.jpg"