# 网站的根URL
baseurl = "https://techqu.github.io/"
# 首页的标题
title = "Quguang's Blog"




# 设置使用的主题
# theme = "maupassant"
theme = "even"
# 设置网站默认的语言，所有的语言翻译文件在i18n目录下，文件名于此处配置的语言代码相同
languageCode = "zh"
defaultContentLanguage = "zh"
# 值为空的话则不启用disqus，因为需要翻墙才能访问，所以我们不启用
disqusShortname = ""
# 取消默认的代码高亮，我们使用prism代码高亮
pygmentsUseClasses = false
pygmentCodeFences = true

## 保持分类的原始名字（false会做转小写处理）
preserveTaxonomyNames = true
## 是否禁止URL Path转小写
disablePathToLower = true

# 每页显示的文章数量用于分页
paginate = 5


# 板块化分
# 权重对应在页面上显示的次序

[author]
  name = "瞿广"
  homepage = "http://www.quguang.wang"

[params]
    subtitle = "记录生活的点滴，学习知识，分享知识"
    keywords = "java,java语言,java语言笔记,techqu,quguang,瞿广,博客,项目管理,python,软件架构,公众号,小程序"
    description = "专注于IT互联网，包括但不限于Java语言(golang)、Go、Android、Python、项目管理、抖音分析、软件架构等"
    busuanzi = true
    # 这里我存放在了主题的static文件夹里，根目录的似乎也可以
    customCSS = ['techqu.css','douban.css']
    # if ['custom.css'], load '/static/css/custom.css' file
    customJS = ['douban.js']
    # if ['custom.js'], load '/static/js/custom.js' file


[[menu.main]]
  identifier = "archives"
   name = "所有文章"
   url = "/archives/"
   weight = 3

#[[menu.main]]
#   name = "markdown示例"
#   url = "/markdown/"
#   weight = 7


# [[menu.main]]
#    name = "网站"
#    url = "/website-list/"
#    weight = 5

[[menu.main]]
    identifier = "about"
    name = "关于"
    url  = "/about/"
    weight = 6

[[params.links]]
  title = "ImportNew"
  name = "ImportNew"
  url = "http://www.importnew.com/"
[[params.links]]
  title = "springboot中文索引"
  name = "springboot中文索引"
  url = "http://springboot.fun/"
[[params.links]]
  title = "springcloud中文索引"
  name = "springcloud中文索引"
  url = "http://springcloud.fun/"

[[params.links]]
  title = "oschina在线工具"
  name = "oschina在线工具"
  url = "http://tool.oschina.net/"



[params.utteranc]
    enable = true
    repo = "techqu/techqu.github.io"    # 存储评论的Repo，格式为 owner/repo
    issueTerm = "pathname"  #表示你选择以那种方式让github issue的评论和你的文章关联。
    theme = "github-light" # 样式主题，有github-light和github-dark两种


#[[params.ads]]
#  title = "广告位测试"
#  url = "https://promotion.aliyun.com/ntms/act/vmpt/aliyun-group/home.html?userCode=jdg9oj97"
#  img = "https://img.alicdn.com/tfs/TB17qJhXpzqK1RjSZFvXXcB7VXa-200-126.jpg"